BUILD_DIR=../build/bootloader
BOOTLOADER_SRCS = $(wildcard *.asm)
BOOTLOADER_OBJS = $(patsubst %.asm,$(BUILD_DIR)/%.bin, $(BOOTLOADER_SRCS))

all: $(BOOTLOADER_OBJS)

$(BUILD_DIR)/%.bin: %.asm $(BUILD_DIR) 
	nasm -f bin $< -o $@

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

clean:
	rm -rf $(BUILD_DIR)
