BUILD_DIR:=build
BOOTLOADER:=$(BUILD_DIR)/bootloader/bootloader.bin
OS=$(BUILD_DIR)/os/os
DISK=$(BUILD_DIR)/disk.img

.PHONY: bootloader os

all: bootloader os

bootloader:
	make -C bootloader
os:
	make -C os
build: bootloader os
	dd if=/dev/zero of=$(DISK) bs=512 count=2880
	dd conv=notrunc if=$(BOOTLOADER) of=$(DISK) bs=512 count=1 seek=0
	dd conv=notrunc if=$(OS) of=$(DISK) bs=512 \
	count=$$(($(shell stat --printf "%s" $(OS))/512)) seek=1

qemu:
	qemu-system-i386 -machine q35 -fda $(DISK)  -gdb tcp::26000 -S
clean:
	make -C bootloader clean
	make -C os clean 
	rm -rf $(BUILD_DIR)
